# URLS
ca_directory = 'https://medium.com/@mikemurpher/x7-finance-contracts-directory-fe3a9fee7b3c'
xchange_buy = 'https://app.x7.finance/#/swap?outputCurrency='
ether_token = 'https://etherscan.io/token/'
ether_address = 'https://etherscan.io/address/'
ether_tx = 'https://etherscan.io/tx/'
bsc_token = 'https://bscscan.com/token/'
bsc_address = 'https://bscscan.com/address/'
bsc_tx = 'https://bscscan.com/tx/'
poly_token = 'https://polygonscan.com/token/'
poly_address = 'https://polygonscan.com/address/'
poly_tx = 'https://polygonscan.com/tx/'
arb_token = 'https://arbiscan.io/token/'
arb_address = 'https://arbiscan.io/address/'
arb_tx = 'https://arbiscan.io/tx/'
opti_token = 'https://optimistic.etherscan.io/token/'
opti_address = 'https://optimistic.etherscan.io/address/'
opti_tx = 'https://optimistic.etherscan.io/tx/'
dex_tools_eth = 'https://www.dextools.io/app/ether/pair-explorer/'
dex_tools_bsc = 'https://www.dextools.io/app/bnb/pair-explorer/'
dex_tools_poly = 'https://www.dextools.io/app/polygon/pair-explorer/'
dex_tools_arb = 'https://www.dextools.io/app/arbitrum/pair-explorer/'
dex_tools_opti = 'https://www.dextools.io/app/optimism/pair-explorer/'

# LINKS
website = 'https://x7.finance'
dashboard = 'https://www.x7finance.org/'
linktree = 'https://linktr.ee/X7_Finance'
medium = 'https://medium.com/@X7Finance'
dune = 'https://dune.com/0xawesomedata/x7r'
twitter = 'https://twitter.com/x7_finance'
discord = 'https://discord.gg/x7finance'
reddit = 'https://www.reddit.com/r/x7finance'
youtube = 'https://youtube.com/channel/UCYnIyBwiomfUUAnjCbNFkqw'
wp_link = 'https://x7.finance/whitepaper'
short_wp_link = 'https://x7community.space/wp-short.pdf'
dac = 'http://shorturl.at/ehnr9'
github = 'https://github.com/x7finance/'
